package.json
src/getAppSyncConfig.js

With this PR, I'm adding:
1- A start-dev command to be used for local development (watches and rebuilds the files, so it can be used with `yarn link`)
2- Handling of table ref inside datasources
3- Support `PIPELINE` resolvers
4- Flatten mappingTemplates, functionConfigurations, dataSources arrays so that we can split the `serverless.yaml` configuration in multiple files (eg. : 
```
mappingTemplates:
- ${file(./data/type1/templates.yml)}
- ${file(./data/type2/templates.yml)}
```
Feedback welcome as always.
Thanks for the effort!

Plugin improvements

---

README.md
src/getAppSyncConfig.js
src/index.js

Fixes #1 + also allows for a custom DynamoDB endpoint to be set, which defaults to `localhost:{dynamoDbPort}`

Support external dynamodb endpoint and define default AWS credentials

---

src/data-loaders/HttpDataLoader.js

I found the AppSync HTTP resolver returns the result in a different structure. This PR aligns the simulator setup with what AppSync does.
Thanks for making this plugin!

Match the HTTP resolver result format

---

src/getAppSyncConfig.js

I was getting error `Missing mapping template undefined` when I tried to let the plugin infer the names of the request and response mapping templates.

Correctly infer mapping template name

---

src/index.js

Fixes a problem where the plugin emits an error when trying to process a `serverless.yml` with no `resources` section. Before this fix, such serverless config would emit:
AppSync Simulator: TypeError: Cannot read property 'Resources' of undefined
The fix uses the optional chaining operator and will force Babel to produce proper guards in the generated library code.

Fix problem where no resources section results in a runtime error

---

README.md
src/getAppSyncConfig.js
src/index.js

As discussed in https://github.com/bboure/serverless-appsync-simulator/issues/22, I've added `custom.appsync-simulator.lambda.loadLocalEnv` boolean option.
> If `true`, the plugin will load all local variables into the lambdas.
> Default would be `false`

Pass all the environment variables to the functions

---

README.md
src/index.js

At @purple-technology we use `Fn::ImportValue` because of our serverless monorepo approach, so adding support for `Fn::ImportValue` mocking is quite crucial for us.
Also we use a lot of serverless variables in the import names, so I added also implementation of key-value notation. 
README:
> ### Key-value mock notation
> 
> In some special cases you will need to use key-value mock nottation.
> Good example can be case when you need to include serverless stage value (`${self:provider.stage}`) in the import name.
> 
> *This notation can be used with all mocks - `refMap`, `getAttMap` and `importValueMap`*
> 
> ```yaml
> provider:
>   environment:
>     FINISH_ACTIVITY_FUNCTION_ARN:
>       Fn::ImportValue: other-service-api-${self:provider.stage}-url
> 
> custom:
> …
```

Add importValueMap option and key-value mock notation

---

src/index.js

Fixes error:
`AppSync Simulator: TypeError: Cannot read property 'wrappedObject' of undefined`
`cfn-resolver-lib` needs to be able to read all resources when checking CloudFormation Conditions, because Conditions are defined in the root of the configurations. This PR ensures that all resources are passed to the node evaluator, instead of just the `Resources` node.
I've tested it in my private repo, and this was needed in order to not get an `undefined TypeError`.
Note: in my testing, I've also noticed that if resources are defined in multiple different yaml-files, and they reference each other, all the "top most" resource files needs the Conditions defined. Ie. with the resources:
- `resource-a.yml`
- `resource-b.yml`
where `resource-a` references `resource-b`, and `resource-b` relies on …

Pass all resources when resolving them

---

package.json
src/getAppSyncConfig.js
yarn.lock

Serverless Appsync plugin supports the specification of multiple schemas. When deploying these schemas are merged into one.
Currently, Serverless Appsync Simulator doesn't support this. If you have multiple schemes defined, you get the error `Type Error - Path must be a string` because the path is an array.
This pull request implements schema merging similarly to the Serverless Appsync.
You can test this feature specifying multiple schemas in the serverless.yml
```
custom:
appSync:
- name: test
schema:
- schema1.graphql
- schema2.graphql
```
Definitions of both the schemas should be available once you run `serverless offline start`
Thanks in advance.

Added support for multiple graphql schemas.

---

README.md

I added it because there was no link to the amplify-appsync-simulator website.
https://github.com/aws-amplify/amplify-cli/tree/master/packages/amplify-appsync-simulator

link to amplify-appsync-simulator

---

README.md
examples/external-functions/mapping-templates/Query.getPosts.request.vtl
examples/external-functions/mapping-templates/Query.getPosts.response.vtl
examples/external-functions/package.json
examples/external-functions/schema.graphql
examples/external-functions/serverless.yml
src/getAppSyncConfig.js

The plugin currently does not support functions that are not defined within the current serverless.yml.
This commit adds a way to define an endpoint for these functions so the can be called anyway as a rest call.
One can make a function callable by defining events.http section.

Added a way to invoke external functions.

---

src/index.js

Add  `AWS::Region` in ref of resource resolvers to allow `cfn-resolver-lib` to map Availability Zones through `FnGetAZs`.  
Closes https://github.com/bboure/serverless-appsync-simulator/issues/55

add region in resources resolvers

---

README.md

Hi there,
So the functions section has an additional parameter that's accepted called "method", but it's not documented.
https://github.com/bboure/serverless-appsync-simulator/blob/e4be7c6e7ed45f788023e04d7ef40d2f45531659/src/getAppSyncConfig.js#L92
If the user does not specify a value for this parameter, axios uses a GET request by default. This is probably not what users want, and the current documentation makes it seem like it would use a POST, but it doesn't.
I didn't change the actual implementation in case users are relying on the default setting, but I want to make this clear for future users.
Cheers!

document the undocumented 'method' param that defaults to 'get'

---

README.md
src/__tests__/__snapshots__/getAppSyncConfig.js.snap
src/__tests__/getAppSyncConfig.js
src/getAppSyncConfig.js

As you advice to me in this issue: [https://github.com/bboure/serverless-appsync-simulator/issues/76](url) I have implemented and tested the connection with my dybamoDb with session token and It work fine because amplify-appsync-simulator is just able to accept the sessionToken parameter!

feat: dynamoDb options is able to accept sessionToken

---

yarn.lock

fix: Upgrade Dependencies

---

package.json
src/__tests__/getAppSyncConfig.js
src/getAppSyncConfig.js
yarn.lock

Support glob pattern and absolute path for schema as well as https://github.com/sid88in/serverless-appsync-plugin/pull/399 .
```
custom:
appSync:
schema:
- path/**/*.graphql
- /path/to/schema.graphql
```

feat: Support glob pattern and absolute path for schema

---

src/getAppSyncConfig.js

Fixes #91
The fix is basically the same as in `serverless-appsync-simulator`, it just took me some time to figure out why the tests were still failing. It turns out that jest was running them on babel output as well on Windows 😅.

Fix schema globbing on Windows

---

README.md
src/getAppSyncConfig.js
src/index.js

An alternate approach to #56 for runtimes where sls invoke is very slow (e.g. runtimes requiring docker)
- Lambda datasources are invoked using the serverless offline invocation endpoint: e.g. `http://localhost:${context.options.lambdaPort}/2015-03-31/functions/${func.name}/invocations`
- If a custom port is provided for sls offline (either via yml or cli) it will be used (default is 3000).

feat: Additional runtime support via Serverless Offline invocation endpoint

---

README.md
package.json
src/data-loaders/RelationalDataLoader.js
src/getAppSyncConfig.js
src/index.js
yarn.lock

Hi, 
I had to make some changes to the amplify-appsync-simulator so that we could truly add support for RDS as a data source.
This repo is a working example: https://github.com/wednesday-solutions/appsync-rds-todo
Please do let me know if there is anything that you would like me to add.
Thank you for taking the time to review this.

feat(rds/dataloader): Add support for using RDS as a dataloader

---

src/data-loaders/RelationalDataLoader.js

Fix for: https://github.com/bboure/serverless-appsync-simulator/issues/126
As `replaceAll` is not supported, we need to use `RegExp` to inject `variableMap`.

fix: variableMap injection by using regex

---

package.json
src/__tests__/__snapshots__/getAppSyncConfig.js.snap
src/getAppSyncConfig.js
yarn.lock

Hi, I tried to fix the issue #142 I've opened previously by following the [migration docs](https://www.graphql-tools.com/docs/migration/migration-from-merge-graphql-schemas) pointed by the [deprecation notice](https://www.npmjs.com/package/merge-graphql-schemas) on the `merge-graphql-schemas` repository.

fix: replace merge-graphql-schemas with @graphql-tools/merge

---

src/getAppSyncConfig.js

I fixed the behavior of `functionConfigurationsLocation`( https://github.com/serverless-appsync/serverless-appsync-simulator/pull/140 ) to be the same as the behavior in [serverless-appsync-plugin](https://github.com/sid88in/serverless-appsync-plugin).
document:
> functionConfigurationsLocation: # defaults to mappingTemplatesLocation (mapping-templates)
code:
https://github.com/sid88in/serverless-appsync-plugin/blob/master/src/get-config.js#L81-L82

fix: default functionConfigurationsLocation refers to mappingTemplatesLocation
